apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  labels:
    app: front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front
          image: "asia-docker.pkg.dev/verdant-option-398406/mbti-repo/mbti-fe:v1"
          securityContext:
            runAsUser: 0
          ports:
            - containerPort: 80
          env:
            - name: NGINX_HOST
              value: back-service
            - name: NGINX_PORT
              value: "4000"
